language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7
    allow_failures:
        - php: hhvm
    fast_finish: true

before_script:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
