name: test

on:
    push:
    pull_request:
    schedule:
        -   cron: '0 5 10 * *'

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ '7.3', '7.4', '8.0' ]
                composer-flags: [ '', '--prefer-lowest' ]

        steps:
            -   name: Install PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: ${{ matrix.php }}

            -   uses: actions/checkout@v2

            -   name: Conditional league/csv installation
                if: ${{ matrix.php == '8.0' }}
                run: composer remove --dev league/csv --no-update

            -   name: Validate composer.json and composer.lock
                run: composer validate --ansi

            -   name: Install dependencies
                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: composer update --ansi ${{ matrix.composer-flags }}

            -   name: Run test suite
                run: composer run-script test --ansi
